
package View;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import library.management.system.UI.HoverEffect;

public class Registration extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String jdbcUrl = "jdbc:mysql://localhost:3306/lms";
    String user = "root";
    String dbpassword = "";
    
    public Registration() {
        initComponents();
        
        HoverEffect.glowEffect(registerBtn);
         HoverEffect.glowEffect(resetBtn);
         HoverEffect.glowEffect(signInBtn);
    }

    public void register() {
    // Retrieve input values
    String name = nameTxt.getText().trim();
    String username = uNameTxt.getText().trim();
    String password1 = String.valueOf(passTxt1.getPassword()).trim();
    String password2 = String.valueOf(passTxt2.getPassword()).trim();

    // Check for empty fields
    if (name.isEmpty() || username.isEmpty() || password1.isEmpty() || password2.isEmpty()) {
        JOptionPane.showMessageDialog(this, "All fields are required!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validate password match
    if (!password1.equals(password2)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match!", "Validation Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Insert data into database
    String sql = "INSERT INTO admin (name, username, password) VALUES (?, ?, ?)";
    try (Connection con = DriverManager.getConnection(jdbcUrl, user, dbpassword);
         PreparedStatement pst = con.prepareStatement(sql)) {

        pst.setString(1, name);
        pst.setString(2, username);
        pst.setString(3, password1);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Registration Successful", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Clear the form after successful registration
        nameTxt.setText("");
        uNameTxt.setText("");
        passTxt1.setText("");
        passTxt2.setText("");

    } catch (SQLException ex) {
        Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(this, "Registration Failed: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSButtonHover1 = new rojerusan.RSButtonHover();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new rojerusan.RSMetroTextPlaceHolder();
        jLabel3 = new javax.swing.JLabel();
        passTxt1 = new rojerusan.RSPasswordTextPlaceHolder();
        uNameTxt = new rojerusan.RSMetroTextPlaceHolder();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passTxt2 = new rojerusan.RSPasswordTextPlaceHolder();
        signInBtn = new rojerusan.RSMaterialButtonRectangle();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        resetBtn = new rojerusan.RSMaterialButtonRectangle();
        registerBtn = new rojerusan.RSMaterialButtonRectangle();
        jLabel10 = new javax.swing.JLabel();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonHover1.setBackground(new java.awt.Color(255, 153, 0));
        rSButtonHover1.setText("X");
        rSButtonHover1.setColorHover(new java.awt.Color(0, 0, 0));
        rSButtonHover1.setColorTextHover(new java.awt.Color(255, 153, 0));
        rSButtonHover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonHover1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonHover1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 50, 30));

        jLabel4.setBackground(new java.awt.Color(255, 153, 0));
        jLabel4.setFont(new java.awt.Font("Source Sans 3 Black", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Up");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, 50));

        jLabel5.setFont(new java.awt.Font("Source Sans 3 SemiBold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        nameTxt.setBackground(new java.awt.Color(0, 0, 0));
        nameTxt.setForeground(new java.awt.Color(255, 102, 0));
        nameTxt.setBorderColor(new java.awt.Color(153, 153, 153));
        nameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        nameTxt.setPhColor(new java.awt.Color(153, 153, 153));
        nameTxt.setPlaceholder("Enter Name");
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 180, 40));

        jLabel3.setFont(new java.awt.Font("Source Sans 3 SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        passTxt1.setBackground(new java.awt.Color(0, 0, 0));
        passTxt1.setForeground(new java.awt.Color(255, 102, 0));
        passTxt1.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        passTxt1.setPhColor(new java.awt.Color(153, 153, 153));
        passTxt1.setPlaceholder("Enter Password");
        jPanel1.add(passTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 180, 40));

        uNameTxt.setBackground(new java.awt.Color(0, 0, 0));
        uNameTxt.setForeground(new java.awt.Color(255, 102, 0));
        uNameTxt.setBorderColor(new java.awt.Color(153, 153, 153));
        uNameTxt.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        uNameTxt.setPhColor(new java.awt.Color(153, 153, 153));
        uNameTxt.setPlaceholder("Enter Username");
        jPanel1.add(uNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 180, 40));

        jLabel6.setFont(new java.awt.Font("Source Sans 3 SemiBold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Source Sans 3 SemiBold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirm Password");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        passTxt2.setBackground(new java.awt.Color(0, 0, 0));
        passTxt2.setForeground(new java.awt.Color(255, 102, 0));
        passTxt2.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        passTxt2.setPhColor(new java.awt.Color(153, 153, 153));
        passTxt2.setPlaceholder("Confirm Password");
        jPanel1.add(passTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 180, 40));

        signInBtn.setBackground(new java.awt.Color(255, 153, 0));
        signInBtn.setText("Sign In");
        signInBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        signInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signInBtnMouseClicked(evt);
            }
        });
        jPanel1.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 50));

        jLabel9.setFont(new java.awt.Font("Source Sans 3 SemiBold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Hello, Friend");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Source Sans 3 Medium", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Already have an account?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        resetBtn.setBackground(new java.awt.Color(255, 102, 0));
        resetBtn.setText("reset");
        resetBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 114, 38));

        registerBtn.setBackground(new java.awt.Color(255, 153, 0));
        registerBtn.setText("Register");
        registerBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 112, 38));

        jLabel10.setBackground(new java.awt.Color(255, 153, 0));
        jLabel10.setFont(new java.awt.Font("Source Sans 3 Black", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Sign");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, 50));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg/register 3.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonHover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonHover1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rSButtonHover1ActionPerformed

    private void signInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signInBtnMouseClicked
        // TODO add your handling code here:
        AdminLogin aL= new AdminLogin();
        this.hide();
        aL.setVisible(true);
    }//GEN-LAST:event_signInBtnMouseClicked

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        register();
    }//GEN-LAST:event_registerBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        nameTxt.setText("");
        uNameTxt.setText("");
        passTxt1.setText("");
        passTxt2.setText("");
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMetroTextPlaceHolder nameTxt;
    private rojerusan.RSPasswordTextPlaceHolder passTxt1;
    private rojerusan.RSPasswordTextPlaceHolder passTxt2;
    private rojerusan.RSButtonHover rSButtonHover1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSMaterialButtonRectangle registerBtn;
    private rojerusan.RSMaterialButtonRectangle resetBtn;
    private rojerusan.RSMaterialButtonRectangle signInBtn;
    private rojerusan.RSMetroTextPlaceHolder uNameTxt;
    // End of variables declaration//GEN-END:variables
}
